### ISSUE TITLE
Run CI every Monday

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_api#46]
Scheudle CI test runner to run every monday lunctime

Context
useful to regular check things are broken

Possible Implementation
```
on:
  push:
  schedule:
    - cron: "0 12 * * 1"
```
